### ISSUE TITLE
Adapt new project setup and documentation style

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-atom-syntax#7]
**Tasks**
- [x] Refactor the `.gitignore` file
- [x] Clean up old project files
- [x] Update to the new documentation style and move to the MIT license
- [x] Add the new project branding assets (SVG and AI files)
- [x] Adapt Travis CI and Circle CI configurations

This issue is part of the [Version 2.0.0](https://github.com/arcticicestudio/northem-atom-syntax/milestone/2)  milestone tracked in the backlog issue #5 .
